import type { ScenarioDefinition } from "./types";

/**
 * Catálogo de escenarios — mantener sincronizado con
 * `agencia/escenarios-centro-mando.md`.
 */
export const SCENARIOS: ScenarioDefinition[] = [
  {
    id: "ing.impl.nueva",
    title: "Nueva implementación IA o automatización",
    summary:
      "El cliente solicita una nueva solución de IA o automatización sobre un proceso de negocio.",
    primaryDept: "ING",
    playbookId: "ing-discovery-to-arch-v1",
    humanGates: [
      "Alcance y precio validados por Matic antes de comprometer fechas o entregables.",
    ],
    steps: [
      "CEO / ING: registrar caso y confirmar objetivo",
      "ING: discovery técnico (sistemas, datos, restricciones)",
      "ING: borrador de arquitectura y riesgos",
      "OPS: plan de hitos y Definition of Done",
      "Puerta humana: propuesta económica y firma de alcance",
    ],
    keywords: [
      "implementación",
      "implementacion",
      "automatizar",
      "automatización",
      "automatizacion",
      "proceso",
      "flujo",
      "integración",
      "integracion",
      "ia",
      "inteligencia artificial",
      "n8n",
      "make",
      "api",
      "erp",
      "crm",
      "ticket",
      "nuevo proyecto",
    ],
  },
  {
    id: "ing.impl.ampliar",
    title: "Ampliación de implementación existente",
    summary: "Cambio de alcance o nuevas funciones sobre algo ya entregado o en curso.",
    primaryDept: "ING",
    playbookId: "ing-change-request-v1",
    humanGates: ["Impacto contractual y replanificación aprobados por Matic."],
    steps: [
      "OPS: vincular al caso / implementación existente",
      "ING: evaluar impacto técnico y esfuerzo",
      "CEO: decidir si requiere change order",
      "Puerta humana: aceptación cliente del ajuste de alcance o precio",
    ],
    keywords: [
      "ampliar",
      "ampliación",
      "ampliacion",
      "añadir",
      "anadir",
      "extra",
      "nueva funcionalidad",
      "cambio de alcance",
      "change request",
      "más módulos",
      "mas modulos",
    ],
  },
  {
    id: "sup.incidente.critico",
    title: "Incidente crítico o bloqueo",
    summary: "Fallo grave, caída o error que impide trabajo o afecta a datos.",
    primaryDept: "SUP",
    playbookId: "sup-p1-triage-v1",
    humanGates: [
      "Comunicación externa si afecta a clientes finales o regulación.",
    ],
    steps: [
      "SUP: acuse y severidad (P1/P2)",
      "ING: diagnóstico y contención",
      "OPS: timeline y comunicación al cliente",
      "Post-mortem si aplica",
    ],
    keywords: [
      "caída",
      "caida",
      "no funciona",
      "error crítico",
      "critico",
      "bloqueo",
      "urgente",
      "producción",
      "produccion",
      "pérdida",
      "perdida",
      "datos mal",
      "incidencia grave",
    ],
  },
  {
    id: "sup.howto",
    title: "Ayuda de uso (how-to)",
    summary: "Preguntas sobre cómo usar el portal o herramientas entregadas.",
    primaryDept: "SUP",
    playbookId: "sup-l1-howto-v1",
    humanGates: [],
    steps: [
      "SUP: respuesta con pasos o enlace a documentación",
      "Si no resuelve → escalar a ING con handoff",
    ],
    keywords: [
      "cómo",
      "como",
      "how to",
      "uso",
      "tutorial",
      "donde está",
      "donde esta",
      "no sé",
      "no se",
      "ayuda",
      "manual",
    ],
  },
  {
    id: "sup.metricas_estado",
    title: "Estado de métricas o entregables",
    summary: "Pedido de resumen de KPIs, valor generado o estado del mes.",
    primaryDept: "SUP",
    playbookId: "sup-status-pack-v1",
    humanGates: [],
    steps: [
      "OPS: compilar métricas acordadas en contrato",
      "SUP: mensaje claro para el cliente con enlaces al panel",
    ],
    keywords: [
      "métricas",
      "metricas",
      "kpi",
      "estado",
      "resumen",
      "informe",
      "qué llevamos",
      "que llevamos",
      "valor",
      "horas ahorradas",
    ],
  },
  {
    id: "mkt.contenido.calendario",
    title: "Calendario / lote de contenido para redes",
    summary: "Generación planificada de piezas para redes sociales.",
    primaryDept: "MKT",
    playbookId: "mkt-weekly-batch-v1",
    humanGates: ["Publicación en cuentas del cliente (según política acordada)."],
    steps: [
      "MKT: brief y calendario propuesto",
      "MKT: borradores de copy y creatividades",
      "Puerta humana: aprobación cliente o Matic según tier",
      "Integración: programación o entrega de assets",
    ],
    keywords: [
      "contenido",
      "redes",
      "instagram",
      "linkedin",
      "calendario",
      "posts",
      "publicar",
      "semanal",
      "redes sociales",
      "social media",
    ],
  },
  {
    id: "mkt.contenido.campaña",
    title: "Campaña puntual",
    summary: "Lanzamiento, evento, promoción o campaña acotada en el tiempo.",
    primaryDept: "MKT",
    playbookId: "mkt-campaign-v1",
    humanGates: ["Presupuesto de ads y mensajes que comprometen oferta."],
    steps: [
      "MKT: objetivo, audiencia y mensajes clave",
      "MKT: plan de medios y creatividades",
      "Puerta humana: aprobación de copy y inversión",
      "Seguimiento y optimización",
    ],
    keywords: [
      "campaña",
      "campana",
      "lanzamiento",
      "promo",
      "promoción",
      "promocion",
      "feria",
      "evento",
      "ads",
      "anuncios",
      "meta ads",
    ],
  },
  {
    id: "mkt.analisis.resultados",
    title: "Análisis de resultados (redes / ads)",
    summary: "Interpretación de métricas y recomendaciones.",
    primaryDept: "MKT",
    playbookId: "mkt-analytics-review-v1",
    humanGates: [],
    steps: [
      "OPS / MKT: verificar datos ingestados",
      "MKT: análisis y conclusiones",
      "MKT: recomendaciones accionables para el siguiente periodo",
    ],
    keywords: [
      "análisis",
      "analisis",
      "resultados",
      "rendimiento",
      "ctr",
      "cpc",
      "alcance",
      "engagement",
      "informe redes",
    ],
  },
  {
    id: "mkt.creative.refresh",
    title: "Renovación de creatividades",
    summary: "Nuevos creativos para combatir fatiga o estacionalidad.",
    primaryDept: "MKT",
    playbookId: "mkt-creative-refresh-v1",
    humanGates: ["Subida a plataformas publicitarias y gasto."],
    steps: [
      "MKT: auditoría de creativos actuales",
      "MKT: nuevas variantes y tests A/B propuestos",
      "Puerta humana: aprobación",
      "Publicación / entrega",
    ],
    keywords: [
      "creatividades",
      "creativos",
      "refresh",
      "renovar",
      "banners",
      "creatives",
      "fatiga",
      "nuevas piezas",
    ],
  },
  {
    id: "vta.lead.inbound",
    title: "Lead entrante (inbound)",
    summary: "Nuevo contacto interesado desde web, formulario o referido.",
    primaryDept: "VTA",
    playbookId: "vta-inbound-qualify-v1",
    humanGates: ["Propuesta económica y condiciones comerciales."],
    steps: [
      "VTA: cualificación ICP y siguiente paso",
      "VTA: respuesta y solicitud de reunión si aplica",
      "ING: mini-diagnóstico si el lead está calificado",
    ],
    keywords: [
      "lead",
      "presupuesto",
      "presupuest",
      "cotización",
      "cotizacion",
      "interesado",
      "contacto nuevo",
      "comercial",
      "contratar",
      "precio orientativo",
    ],
  },
  {
    id: "vta.seguimiento",
    title: "Seguimiento comercial",
    summary: "Follow-up tras propuesta, reunión o silencio del cliente.",
    primaryDept: "VTA",
    playbookId: "vta-followup-v1",
    humanGates: ["Descuentos, plazos firmes o compromisos especiales."],
    steps: [
      "VTA: revisar contexto del CRM",
      "VTA: mensaje de seguimiento personalizado",
      "CEO: intervenir si hay riesgo de pérdida",
    ],
    keywords: [
      "seguimiento",
      "follow up",
      "followup",
      "recordatorio",
      "propuesta enviada",
      "reunión pasada",
      "reunion pasada",
      "no contestáis",
      "no contestais",
    ],
  },
  {
    id: "vta.discovery.prep",
    title: "Preparación de discovery",
    summary: "Brief y preguntas antes de una reunión de descubrimiento.",
    primaryDept: "VTA",
    playbookId: "vta-discovery-brief-v1",
    humanGates: [],
    steps: [
      "VTA: investigación de empresa y pain points",
      "VTA: guion de discovery y hipótesis",
      "OPS: logística de la reunión",
    ],
    keywords: [
      "discovery",
      "reunión comercial",
      "reunion comercial",
      "preparar reunión",
      "brief comercial",
      "primera reunión",
      "primera reunion",
    ],
  },
  {
    id: "vta.objecion",
    title: "Objeción (precio / prioridad)",
    summary: "Cliente duda por precio, timing o prioridad interna.",
    primaryDept: "VTA",
    playbookId: "vta-objection-v1",
    humanGates: ["Precio final y términos negociados."],
    steps: [
      "VTA: clasificar objeción",
      "CEO: líneas rojas y alternativas permitidas",
      "Puerta humana: oferta final",
    ],
    keywords: [
      "objeción",
      "objecion",
      "caro",
      "presupuesto ajustado",
      "no tenemos budget",
      "prioridad",
      "más barato",
      "mas barato",
      "competidor",
    ],
  },
  {
    id: "sup.onboarding",
    title: "Onboarding de cliente",
    summary: "Inicio formal: accesos, calendarios, contactos, kick-off.",
    primaryDept: "SUP",
    playbookId: "sup-onboarding-v1",
    humanGates: ["Credenciales de producción del cliente."],
    steps: [
      "SUP: checklist de bienvenida",
      "OPS: plan de hitos visible en el portal",
      "ING: preparación de entornos si aplica",
    ],
    keywords: [
      "onboarding",
      "empezar",
      "inicio",
      "kick off",
      "kickoff",
      "accesos",
      "alta",
      "bienvenida",
    ],
  },
  {
    id: "sup.escalado.tecnico",
    title: "Escalado técnico (L1 → ingeniería)",
    summary: "Soporte detecta que hace falta intervención de ingeniería.",
    primaryDept: "SUP",
    playbookId: "sup-escalate-engineering-v1",
    humanGates: ["Acceso a sistemas del cliente para depuración."],
    steps: [
      "SUP: ticket con reproducción y logs mínimos",
      "ING: priorización y diagnóstico",
      "SUP: comunicación al cliente del ETA",
    ],
    keywords: [
      "escalar",
      "ingeniería",
      "ingenieria",
      "bug",
      "técnico avanzado",
      "tecnico avanzado",
      "desarrollo",
      "arreglar código",
    ],
  },
  {
    id: "ops.entrega.hito",
    title: "Cierre de hito de proyecto",
    summary: "Validación de una fase del roadmap antes de continuar.",
    primaryDept: "OPS",
    playbookId: "ops-milestone-close-v1",
    humanGates: ["Aceptación explícita del cliente en hitos contractuales."],
    steps: [
      "OPS: checklist DoD del hito",
      "ING / MKT: evidencias de entrega",
      "Cliente: confirmación en portal o acta",
    ],
    keywords: [
      "hito",
      "fase",
      "cerrar fase",
      "aceptación",
      "aceptacion",
      "uat",
      "entrega parcial",
      "milestone",
    ],
  },
  {
    id: "ops.calidad",
    title: "Control de calidad interno",
    summary: "Revisión antes de exponer entregable al cliente.",
    primaryDept: "OPS",
    playbookId: "ops-quality-gate-v1",
    humanGates: [],
    steps: [
      "OPS: revisar contra criterios acordados",
      "Devolver a ING/MKT si no cumple",
      "Aprobar envío al cliente",
    ],
    keywords: [
      "calidad",
      "qa",
      "revisión interna",
      "revision interna",
      "quality gate",
      "antes de enviar",
    ],
  },
  {
    id: "ing.auditoria.proceso",
    title: "Auditoría / mapeo de proceso",
    summary: "Entender el as-is y oportunidades de IA sin comprometer build aún.",
    primaryDept: "ING",
    playbookId: "ing-process-audit-v1",
    humanGates: [],
    steps: [
      "ING: taller o cuestionario con stakeholders",
      "ING: mapa de proceso y cuellos de botella",
      "CEO: priorización de oportunidades con el cliente",
    ],
    keywords: [
      "auditoría",
      "auditoria",
      "mapear proceso",
      "as is",
      "asis",
      "cuellos de botella",
      "oportunidades",
      "diagnóstico",
      "diagnostico",
    ],
  },
  {
    id: "ing.integracion",
    title: "Diseño de integración",
    summary: "Conectar sistemas vía API, webhooks, RPA o iPaaS.",
    primaryDept: "ING",
    playbookId: "ing-integration-design-v1",
    humanGates: ["Credenciales, compliance y acceso a entornos."],
    steps: [
      "ING: contrato de datos y flujo",
      "ING: especificación técnica y pruebas",
      "OPS: despliegue y monitorización",
    ],
    keywords: [
      "webhook",
      "conector",
      "sincronizar",
      "sincronización",
      "sincronizacion",
      "zapier",
      "ipaas",
      "oauth",
    ],
  },
  {
    id: "ceo.priorizacion",
    title: "Priorización multi-frente",
    summary: "Varias peticiones; ordenar impacto, dependencias y dueños.",
    primaryDept: "CEO",
    playbookId: "ceo-prioritize-v1",
    humanGates: ["Fechas comprometidas con el cliente."],
    steps: [
      "CEO: inventario de peticiones abiertas",
      "CEO: matriz impacto vs esfuerzo",
      "Comunicar plan al cliente en el portal",
    ],
    keywords: [
      "priorizar",
      "prioridad",
      "varias cosas",
      "todo a la vez",
      "orden",
      "qué antes",
      "que antes",
      "backlog",
    ],
  },
  {
    id: "ceo.conflicto_alcance",
    title: "Conflicto de alcance",
    summary: "Desalineación sobre qué está incluido en el contrato.",
    primaryDept: "CEO",
    playbookId: "ceo-scope-mediation-v1",
    humanGates: ["Change order o addendum firmado."],
    steps: [
      "CEO: revisar contrato y entregables firmados",
      "Propuesta de resolución al cliente",
      "Puerta humana: acuerdo por escrito",
    ],
    keywords: [
      "alcance",
      "no estaba incluido",
      "incluido",
      "contrato dice",
      "desacuerdo",
      "scope",
      "extra no acordado",
    ],
  },
  {
    id: "cli.formacion",
    title: "Formación / taller",
    summary: "Capacitación en uso de soluciones entregadas.",
    primaryDept: "SUP",
    playbookId: "del-training-v1",
    humanGates: ["Calendario y asistencia confirmada."],
    steps: [
      "SUP: necesidades de audiencia",
      "ING: materiales y demos",
      "Sesión en vivo o grabación",
    ],
    keywords: [
      "formación",
      "formacion",
      "taller",
      "training",
      "capacitación",
      "capacitacion",
      "enseñar",
      "ensenar",
      "curso",
    ],
  },
  {
    id: "cli.renovacion",
    title: "Renovación de contrato",
    summary: "Fin de periodo o extensión del acuerdo.",
    primaryDept: "VTA",
    playbookId: "vta-renewal-v1",
    humanGates: ["Términos económicos y duración finales."],
    steps: [
      "VTA: propuesta de renovación con valor demostrado",
      "CEO: aprobación de condiciones",
      "Firma y actualización en portal",
    ],
    keywords: [
      "renovación",
      "renovacion",
      "renovar",
      "fin de contrato",
      "ampliar contrato",
      "extensión",
      "extension",
    ],
  },
  {
    id: "sys.cron.semanal_mkt",
    title: "Informe semanal automático (redes)",
    summary: "Job programado que genera borrador de informe para revisión.",
    primaryDept: "MKT",
    playbookId: "mkt-weekly-report-auto-v1",
    humanGates: ["Envío al cliente tras revisión humana si la política lo exige."],
    steps: [
      "Sistema: recopilar métricas",
      "MKT: narrativa y destacados",
      "Puerta humana: envío",
    ],
    keywords: [
      "cron",
      "automático semanal",
      "automatico semanal",
      "reporte semanal",
    ],
  },
  {
    id: "sys.ingest.metricas",
    title: "Ingesta de métricas (integraciones)",
    summary: "Conectar APIs de plataformas para alimentar el panel.",
    primaryDept: "OPS",
    playbookId: "mkt-metrics-ingest-v1",
    humanGates: ["Tokens OAuth y permisos del cliente."],
    steps: [
      "OPS: solicitar accesos",
      "ING: conectores y validación de datos",
      "MKT: verificación de cuadros de mando",
    ],
    keywords: [
      "ingesta",
      "conectar meta",
      "conectar linkedin",
      "token",
      "oauth",
      "api métricas",
      "api metricas",
    ],
  },
  {
    id: "gen.triaje",
    title: "Triaje general (sin clasificación clara)",
    summary: "Entrada ambigua; el centro de mando clasifica antes de ejecutar.",
    primaryDept: "CEO",
    playbookId: "ceo-intake-triage-v1",
    humanGates: ["Clasificación final y asignación de dueño."],
    steps: [
      "CEO: resumen de la petición en 3 líneas",
      "Hasta 3 preguntas cerradas al cliente",
      "Asignar escenario y playbook definitivo",
    ],
    keywords: [],
  },
  {
    id: "ing.poc.rapido",
    title: "POC / prueba rápida",
    summary: "Validación acotada en tiempo y datos para reducir riesgo.",
    primaryDept: "ING",
    playbookId: "ing-poc-sprint-v1",
    humanGates: ["Límites de datos sensibles y tiempo máximo de POC."],
    steps: [
      "ING: alcance POC en 1 página",
      "Implementación mínima en entorno aislado",
      "Demo y decisión go/no-go",
    ],
    keywords: [
      "poc",
      "prueba de concepto",
      "prueba rápida",
      "prueba rapida",
      "mvp",
      "piloto rápido",
      "piloto rapido",
      "dos semanas",
      "1 semana",
    ],
  },
  {
    id: "ops.reporte.valor",
    title: "Informe de valor para comité",
    summary: "Documento ejecutivo: dónde se genera valor vs inversión.",
    primaryDept: "OPS",
    playbookId: "ops-value-report-v1",
    humanGates: ["Cifras contractuales y mensajes financieros."],
    steps: [
      "OPS: consolidar métricas del periodo",
      "CEO: mensaje estratégico",
      "Puerta humana: revisión final antes de comité",
    ],
    keywords: [
      "comité",
      "comite",
      "junta",
      "dirección",
      "direccion",
      "informe valor",
      "roi",
      "retorno",
      "justificar inversión",
      "justificar inversion",
    ],
  },
];

const byId = new Map(SCENARIOS.map((s) => [s.id, s]));

export function getScenarioById(id: string): ScenarioDefinition | undefined {
  return byId.get(id);
}

export function getFallbackScenario(): ScenarioDefinition {
  return byId.get("gen.triaje")!;
}
